### ISSUE TITLE
Move button

### ISSUE THREAD

**Issue by khiemntu** [dounets/CarTOS2D#19]
![8-10-2016 8-56-31 am](https://cloud.githubusercontent.com/assets/9651721/17539444/908a0de0-5ed8-11e6-9abb-d041407c51be.png)

**Comment by khiemntu** [comment]
move 2 button vào gần nút xe

**Comment by lucduong** [comment]
Done. ✌️ 
![19_toolbar](https://cloud.githubusercontent.com/assets/2667418/17540699/831077ee-5ee2-11e6-95f8-277445a67340.png)
